### ISSUE TITLE
add contact no. in the contact section

### ISSUE THREAD

**Issue by SHREYANSH-sm** [Nishkarsh01/shreyanshportfolio#10]
Add a contact button in the contact section using href="tel:5551234567"

example code:
`<a href="tel:5551234567">Call (555)123-4567</a>`

**Comment by Nishkarsh01** [comment]
Successfully added contact no. in the contact section

![1](https://user-images.githubusercontent.com/60971213/105983498-db0c4800-60be-11eb-85eb-538c9a1f0d40.png)
